### PR TITLE
Compile assets in nightly tests, and use Node 20 everywhere

### PR DESCRIPTION
**Pull request by zerolab**
Part of #22

Also standardises on Node 20 (LTS) everywhere. We had node 21 in docs and `devcontainer.json`, Node 16 in `.nvmrc` and Node 18 as default in the GitHub Actions ([ref](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md))

### CODE REVIEW

**Comment by tomusher** [comment]
Should we update the `devcontainer.json` to match the node version too?

**Comment by zerolab** [comment]
oh, I missed that one. will do

**Comment by zerolab** [comment]
@tomusher done. and rebased to keep the commits clean

**Comment by tomusher** [comment]
Perfect thanks @zerolab !

**Pull request merged**
